# Generated by Django 2.0.4 on 2018-04-03 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='albu_title',
            new_name='album_title',
        ),
    ]
