# Generated by Django 2.0.4 on 2018-04-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20180403_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='genere',
            new_name='genre',
        ),
    ]
